default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: devTrackPerex

test:
  <<: *default
  database: devTrackPerex

production:
  <<: *default
  database: prodTrackPerex
